### ISSUE TITLE
[FEATURE] Make "roll damage manually" the default

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#110]
There are many features which neccessitate that the attack roll and damage rolls are seperate. Some examples include the shield spell and the paladin's divine smite. You are not supposed to know the result of the damage roll before using features like these.

Thus, I think manually rolling damage should be the default, while the option to always roll attack and damage together should remain as an option.

**Comment by MangoFVTT** [comment]
The intent of this module is to keep behaviour as close to Better Rolls as possible, since that is what the majority of people want from it. As such, since it is a quick roll module after all, quick rolling should be enabled by default to not inconvenience 99% of people. You always have the option to set the setting as per your wishes for all players, which is a one-time thing that won't take too much effort.
