### ISSUE TITLE
[FEATURE] Allow "Consume uses" to be selected as the default for spell "quick rolls."

### ISSUE THREAD

**Issue by KasaiSV** [MangoFVTT/fvtt-ready-set-roll-5e#123]
**Is your feature request related to a problem? Please describe.**
Currently, when a spell is set up with "at-will" charges, the default for the "quick rolls" option to determine if the spell consumes one of its charges is un-selected, as seen in the screenshots below.
![image](https://user-images.githubusercontent.com/73495745/210120785-cd575ac9-09c5-43cf-965f-f31f3fddbbaf.png)
![image](https://user-images.githubusercontent.com/73495745/210120795-fb9572d8-1489-456d-9ea4-589a0990d228.png)

Unfortunately, given that many of the new monsters introduced in the MoTM book use charges for spellcasting rather than spell slots, many monsters are now using their spells through the "at-will" spell preparation mode in FVTT instead of through the "prepared" option (which uses the standard spell slots). This means that by default, all spells set up in this way do not consume their charges. This requires either manually selecting this box for every spell a caster has, or manually tracking the charges rather than using FVTT.

**Describe the solution you'd like**
In the same way that spells will, by default, consume a spell slot even when "quick rolls" are enabled, having spells, by default, consume their uses would be very helpful. An alternative would be to have an option in the base module settings that would allow for consumption to be on by default.

**Comment by MangoFVTT** [comment]
This actually was unintended behaviour. Consumables for spells specifically are meant to be configured on a per casting basis via the pop-up config, specifically because they are the most fluid kind of item in terms of consumable charges and having a fixed config made little sense. Thanks for the catch, this has been fixed and moving forward spells should bring up the correct config pop-up for consuming uses (with the default being true).

![image](https://user-images.githubusercontent.com/110994627/211515279-a2802380-f817-4296-a9b6-d040dc1084b2.png)
