### ISSUE TITLE
[BUG] Cannot apply damage as a player, permission issue

### ISSUE THREAD

**Issue by Ornstrias** [MangoFVTT/fvtt-ready-set-roll-5e#124]
**Description**
Hello
When my player clics on apply damage, it says it doesn't have permission, I am new to foundry so maybe I'm missing something ?

**Steps to Reproduce**
1. Target Monster "A" as a player
2. Click on you attack (here battleaxe in Inventory)
3. When the damage are displayed click on apply damage
4. See 'player xxx permisison error"

**Versions**
 - Module: [1.3.13]
 - dnd5e: [2.0.3]
 - Foundry: [10.291]

**Comment by MangoFVTT** [comment]
This is intentional and in line with Foundry's permission system. Users can only apply damage to tokens that they own. For players, this is generally only their own token. For GM's, this should be everything. The intent is to avoid abuse where players apply damage multiple times or apply the wrong damage to cheat.

**Comment by Ornstrias** [comment]
Thank you for your answer :)
