### ISSUE TITLE
QuickRoll how to work with it [BUG]

### ISSUE THREAD

**Issue by AngryBeaver** [MangoFVTT/fvtt-ready-set-roll-5e#132]
**Description**
I have a module that depends on the roll result, and this module does not work with ready-set-roll as the default behaviour of
game.actors.get("0fEOpwc1zkQuIl99").rollSkill("acr") => has changed from retruning a Promise Roll to a Promise QuickRoll.

1) is it possible to return Roll again ?
2) if not is it possible to get some stable structure that i can get to the roll through quickroll.

current workaround for me is if i detect a quickroll:

game.actors.get("0fEOpwc1zkQuIl99").rollSkill("acr").then(c=>console.log(c.fields[2][1].roll));

wich feels like this will break any minute :-)

**Comment by MangoFVTT** [comment]
Retrieving the original roll from a quick roll is not a particularly trivial matter unfortunately, since in some cases the quick roll can contain multiple rolls at the same time (specifically, for items). For actor rolls such as rollSkill however, it's a bit simpler. You've already pretty much identified that it is inside the fields value, but instead of hardcoding it to [2] you should be able to find the field that has "check" as it's key value, and then access .roll from there.

![image](https://user-images.githubusercontent.com/110994627/212546805-295fe128-6330-4f1d-9ba3-133dcabd8662.png)

The key will be "check" for any ability check, saving throw, or skill roll. For item rolls, you instead need to search for fields that have "attack" or "damage" as their key value.

It's not exactly the cleanest method of access, but at the moment that's the best you can get. I will update this ticket if there's any simpler way to access the original roll in future.
