### ISSUE TITLE
[BUG] Upcasting spells with a flat value in the main formula causes issues

### ISSUE THREAD

**Issue by OxTailSafu** [MangoFVTT/fvtt-ready-set-roll-5e#176]
**Description**
I'll try to make sense of this, apologies as I am not an expert on Foundry and how it works. If you put a spell that does not contain a rolled formula in the first line but has some rolled values in the additional lines, trying to upcast the spell causes various issues.

![image](https://user-images.githubusercontent.com/123988485/232355418-205053e7-be0a-485b-9442-c00a117416e6.png)

Here's the spell in question that has issues. The spell normally heals 25 + your spellcasting modifier, while also gaining a bonus to the healed amount based on the target's constitution modifier. The bonus is a number of d6's equal to their constitution modifier. As you can see, I have all of the amounts listed since my party is varied. The spell also gains a bonus when you upcast it, the bonus being 2d6 per spell level above 4th.

![image](https://user-images.githubusercontent.com/123988485/232355921-b8997aa0-902b-420c-bec5-cefa1d369b82.png)

The above picture shows the issue in question. The base healing formula has suddenly changed to 25 + spellcasting mod + 5d6 instead of being 25 + spellcasting mod + 2d6. More curiously, the 2d6 bonus that's supposed to be rolled for having a +2 constitution modifier is now only rolling 1d6. There is no error code on the console as far as I could see.

I tested this in just the base version of DnD 5e and the base ruler appears to be working. I was able to get a description of the issue from someone on the Foundry discord who provided a workaround for this issue. The solution of course, was to make the formula 0d6+25+spellcasting mod, and that soon enough resolved the issue.

![image](https://user-images.githubusercontent.com/123988485/232357004-cca0558b-d4b8-4484-b97d-dd5f9e9fa5f2.png)

**Steps to Reproduce**
1. Create a spell with only a flat value for healing or damage. 
2. Ensure that the spell can be upcasted and has scaling that involves a rolled amount.
3. Add additional rolled formulas below the the flat formula.
4. Upcast the spell and note the values being incorrect.

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.1.5]
 - Foundry: [10.291]

**Comment by MangoFVTT** [comment]
RSR does nothing itself in terms of handling upcasting rolls, and most likely the issues you are seeing are simply a byproduct of the rolls being split up into different fields. Unfortunately, this means I can't really do much about your particular use-case since that is all handled by core foundry, and then simply split up by RSR post-rolling.

The solution to use 0d6 at the start of the first field is unfortunately the only way to "fix" this at the time being. Short of foundry making upscaling more accessible or a complete rewrite of how RSR parses damage (even then, I'm not sure if it would be possible) there is no other real option.

**Comment by OxTailSafu** [comment]
No problem at all, I appreciate the reply and can understand if a fix for something like this would be outside your control (in the case of Foundry changing their functions) or you trying to fix it with RSR!
