### ISSUE TITLE
[BUG] Right clicking the chat card and applying damage uses the attack roll, not the damage roll.

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#178]
**Description**
Right clicking the chat card and applying damage uses the attack roll, not the damage roll.
Using current versions of dnd5e and ready set roll.

**Comment by MangoFVTT** [comment]
I am unable to reproduce this problem in RSR 1.5.1, tokens are correctly reducing the total damage of the card rather than the attack or ability check. Please create a new bug ticket with more information (preferably video proof and item information) if the problem re-occurs.

![video](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/5dec3cac-09d7-4e7c-84dc-3cdfa261897c)
