### ISSUE TITLE
[FEATURE] Ability to split damage types without quick rolls

### ISSUE THREAD

**Issue by AquaZera** [MangoFVTT/fvtt-ready-set-roll-5e#182]
I love the ability to automatically have the damage types be separated, but my players and I almost always have some sort of situational bonus to add making the quick rolls a non possibility. It would be great if there was a way to have the nice damage card be separate from using quick rolls.

**Comment by MangoFVTT** [comment]
This is unfortunately not possible to implement with RSR, due to the complicated nature of how damage is split into separate fields for cards during the quick roll. However, there is almost definitely some other module that does exactly what you're asking for, so I would check with the FoundryVTT discord and ask around there 🙂
