### ISSUE TITLE
[BUG] If critical is set to true by a hook, the chat message doesn't show it as a critical hit

### ISSUE THREAD

**Issue by kaelad02** [MangoFVTT/fvtt-ready-set-roll-5e#184]
**Description**
Hi, Advantage Reminder author here. I was working on some better compatibility between AR and RSR and noticed an issue with damage rolls. AR works through a `dnd5e.preRollDamage` hook to check if any active effects say to turn it into a critical hit. It will roll the extra damage (e.g. rolls `2d8 + 3` instead of the normal `1d8 + 3`) but it looks like a normal roll in the chat. It even has the plus button to turn it into a critical hit and rolls too much extra dice (rolls an extra `2d8` as crit damage).

Here's the expanded damage roll. It has the correct damage but doesn't appear split like a crit normally is.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/19502084/d220abba-2f30-46db-926b-eb5343f7845e)

Here's a screenshot after pressing the plus sign
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/19502084/406ccef8-4b58-4744-a70a-6e6f39c3d115)

Could we fix it so if a hook turns the attack into a critical hit then it's recognized as such?

**Steps to Reproduce**
1. Setup a hook to force the next damage roll to be a crit:
```js
Hooks.once("dnd5e.preRollDamage", (item, config) => config.critical = true);
```
2. Click on a weapon to make an attack and roll damage
3. Look at the chat message it creates
4. See that it rolled critical damage but it appears like a normal roll

**Versions**
 - Module: 1.5.1
 - dnd5e: 2.1.5
 - Foundry: 10.291

**Other Modules**
None, reproducible with just the hook. But I'd like it to work with the upcoming Advantage Reminder release v3.2.0

**Comment by MangoFVTT** [comment]
@kaelad02 The issue you are running into here is primarily that RSR computes its critical damage separately in order to be able to display it as it does. To put it shortly: when an item with damage is rolled, RSR will rollDamage ALWAYS without crit, and then add in crit damage afterwards if the item roll was marked as a critical. Since you're hooking into preDamage, you're overriding the always without crit that RSR enforces, causing unintended behaviour.

The best way to force a crit for RSR would be to pass in `{ isCrit: true }` as one of the item uses options. You can do this similarly to what you're doing already but by hooking into the item use Hook instead

`Hooks.once("dnd5e.useItem", (item, config, options) => options.isCrit = true);`

Note that this will only work as intended once the fix for #163 is released (should be release 1.5.2)

**Comment by MangoFVTT** [comment]
Mistakenly closed this 😅 Will close when you confirm if this solution works out for you

**Comment by kaelad02** [comment]
I was worried about something like that. Wow, that's really early. Is that so the data is stored in flags on the chat message or something to be referenced later? Also, does that work if you've configured RSR to Always Roll Damage Manually?

I've refactored some code to make it easier for me to make these adjustments. I'll check it out tomorrow and see how feasible this change would be.

**Comment by kaelad02** [comment]
Okay, I can get it to work using the `dnd5e.useItem` hook. It won't work with those midi flags that cancel critical hits (e.g. `flags.midi-qol.fail.critical.all` for Adamantine Armor) but I can add a little note about that in my readme. Not the end of the world. Still better support than what I had originally with RSR. Thanks for the help.

**Comment by MangoFVTT** [comment]
Midi and RSR do not support each other regardless, so I wouldn't be too concerned with their flags not interacting in the right way. Glad to help, let me know if there's anything else you need 👍

**Comment by kaelad02** [comment]
I know that. To clarify, Advantage Reminder uses the same active effect keys that Midi defines for advantage/disadvantage/critical and lets you use them without Midi. So if all you were looking for was adv/dis support you can use AR instead of the much larger Midi.
