### ISSUE TITLE
[FEATURE] MidiQOL-esque active effects

### ISSUE THREAD

**Issue by ZeroXNoxus** [MangoFVTT/fvtt-ready-set-roll-5e#226]
**Describe the solution you'd like**
Add a list of options to the active effects drop-down for some really useful flags on the Token. To name a few:
- Ability Check/Save Dis-/Advantage
- Attack Roll Dis-/Advantage
- Damage Vulnerbility/Resistance/Immunity Flag

**Comment by MangoFVTT** [comment]
Ready Set Roll is not designed for that sort of automation, nor intended to be. It is a relatively automation-lite alternative, designed for people who explicitly want that instead of Midi-QOLs automation-heavy feature set. 

As far as flags go, I believe [Advantage Reminder](https://github.com/kaelad02/adv-reminder) uses Midi flags and has some support for RSR, and damage vuln/resistance/immunity is now automatically calculated by RSR if you have the correct setting enabled.
