### ISSUE TITLE
[FEATURE] Multiple damage type option

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#228]
**Is your feature request related to a problem? Please describe.**
Some spells and features allow you to choose the damage type of the spell or feature, for example chaos bolt, chromatic orb and the Way of the Ascendant Dragon monk's Draconic Disciple feature. It would be nice if you could put a toggle on the chat cards to override the damage type to be what you want it to be, maybe only if you have a certain box ticked on the item card

**Describe the solution you'd like**
the option to have either the damage type to be chosen before it rolls or the ability to change the damage type on an existing chat card provided that for either there is a multi damage check box or something is ticked on the actual item.

**Describe alternatives you've considered**
Ignoring the damage types and just manually keeping in mind that it should be a, b or c

**Additional context**
Really enjoy the enhanced damage buttons and reroll of damage rolls that were recently added and feel this could be the next step.
well done so far

**Comment by MangoFVTT** [comment]
With recent changes in dnd 3.1 and how it rolls and processes damage type, as well as the addition of drop-down menus in roll configuration dialogs, this should now be made as a request in the dnd5e github instead of RSR. A configurable damage menu could easily be added to the config popup in the same way that the summons have been.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/5563b000-308a-45d0-871d-731d48dccbae)

Will be closing the ticket as no longer applicable to RSR.
