### ISSUE TITLE
[BUG] Critical Damage Application With Multiple Rolls Enabled

### ISSUE THREAD

**Issue by TLad75** [MangoFVTT/fvtt-ready-set-roll-5e#276]
**Description**
First off, I just started moving to Foundry and wow I love this mod, thank you!  I am not entirely sure if this is a bug, intended behavior or if I am doing something wrong.  I have 'Always Roll Multiple Dice' enabled in RSR as well as 'Critical Damage Maximize Dice' enabled in the DnD5e core settings.  When rolling attack rolls and if either D20 is a 20 it will calculate critical damage as expected by maxing the base damage, add the ability modifier and then do a roll for the critical damage on top of that.  This can cause some confusion when multiple rolls are enabled and the right hand roll is the nat 20 (right hand roll is used for advantage when the situation calls for it).

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/65173996/a817ca5d-1a2f-41a4-9900-fd66c6b63df1)

I have seen in a couple issues here ([120](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/120) and specifically [262](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/262)) that when these settings are applied then this maximized critical damage should apply to the additional damage value (on the right side) instead which would make determining the normal damage when the attack is not actually a crit much easier as the rolled damage would have the modifiers added and the it would be + Maxed damage dice Crit on the right side.

This is from a D&D stream that aired roughly a year ago but this is what I am attempting to reproduce (4d8 + 9 on the left then the maxed 4d8 on the right):
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/65173996/3663ed71-68d7-40e7-8fc2-347e3a8efabb)

**Steps to Reproduce**
1. Install versions of Foundry, dnd5e, RSR and the dependency listed below.
2. Enable modules.
3. In dnd5e settings enable 'Critical Damage Maximize Dice'.
4. In Ready Set Roll settings enable 'Always Roll Multiple Dice'.
5. Roll attack rolls until you get a with either of the attack rolls 20.

**Versions**
 - Module: [2.1.5]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Other Modules**
libWrapper 1.12.13.0

**Comment by MangoFVTT** [comment]
@TLad75 the issue with maximizing dice on the right is that dnd5e now supports adding additional melee damage dice and damage (e.g. for brutal critical), which _shouldn't_ be maximized by powerful critical. The intended behaviour of powerful critical is always to maximize the original dice (i.e. the left hand side). 

The issue is, both left hand side and right hand side rolls are one roll each. I cannot maximize part of a roll, so the only options I have are to maximize the left hand side (which gives the correct powerful critical result), or to maximize the right hand side entirely, bonus damage included. Neither option is ideal of course.

I will attempt to investigate a potential way to mimic maximizing internally, thereby hopefully taking the maximizing back to the right hand side and maximizing the roll partially (excluding bonus dice), but I expect this will be quite tricky.

**Comment by TLad75** [comment]
Ah thank you for the detailed explanation, that makes sense. I'm guessing I was looking at an older version of the mod since that stream was from about a year ago which was on V10 of Foundry based on release notes.

If it is possible to mimic maximizing internally that would be an awesome addition to multiple rolls to streamline combat.  Since it is not how the module works currently, feel free to close this bug out if you would like or move it to a feature request.  I will get my players into the habit of rolling advantage/disadvantage with shift and ctrl which should hopefully be easy to do since they'll be learning Foundry from the ground up.  Thanks again!

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer handles the internal logic of calculating crits and instead allows the system to do so internally.  As such, this ticket is no longer related to RSR and can be considered resolved from the standpoint of this module.
