### ISSUE TITLE
[FEATURE] Show D20 for Quick Rolls Players ONLY

### ISSUE THREAD

**Issue by friction1** [MangoFVTT/fvtt-ready-set-roll-5e#337]
**Is your feature request related to a problem? Please describe.**
Show D20 Rolls for Quick Rolls affects GMs and Players the same.

**Describe the solution you'd like**
It would be great if there were an option to allow the D20 roll to show for players' rolls but the players don't get to see the D20 of the GM when publically rolled. The GM gets to see all the rolls always.

<img width="306" alt="Screenshot 2024-02-13 at 7 35 55 PM" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/11384891/98f268ee-0948-464e-9259-5d020dbdcfe0">

**Comment by MangoFVTT** [comment]
@friction1 I'm unclear what the point of this would be. If the chat card is public, then players can simply expand the tooltip to see the d20 result anyway, hiding the d20 icon on the main display wouldn't really affect anything? Can you elaborate on what the use case for this would be?

**Comment by friction1** [comment]
I didn’t realize you could see the math in the expanded card. Ideally we like to play where the GM’s total results are public knowledge but the actual d20 roll is not so that players can’t metagame the precise monster bonuses. 

I’m proposing a checkbox or dropdown option to hide all of the GMs d20 rolls to players.

**Comment by MangoFVTT** [comment]
In that case, this would be a request to make to the dnd5e system github instead of RSR. RSR now uses purely the system setup for chat messages, which means it only adds onto that content rather than creates it itself. If dnd5e implements a system to do what you wish and hide the tooltip from players, then RSR should automatically also work the same way 👍
