### ISSUE TITLE
[BUG] Dialog confirmation on resource consume as ammunition

### ISSUE THREAD

**Issue by Phentei** [MangoFVTT/fvtt-ready-set-roll-5e#345]
**Description**
Before the 3.0 Update of DND5e, I had set my player's bow to consume the primary attribute as a resource.
This allowed the player to have the associated resource bar directly visible on his token.
Now, when the player attack roll with the bow, a dialog appears to confirm that the resource to be consume.

I've first ask for help on FoundryVTT/DND5E Discord section but it seems that's the normal way in this case and if it didn't appear before the update was cause of a module was skipping it.
I assume that was a RSR feature.

**Steps to Reproduce**

- Take a weapon that consume ammunition (longbow for example)
- Define its resource consumation as Attribute and select resources.primary.value in the dropdown
- Set de values of the Primary Resource (20/20 for example).
- Roll attack for the weapon

=> The dialog shows

![RSR_Dialog](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/7251446/c72954cb-a4e6-431a-994b-41a8052db979)
_(Please ignore in the screen the resource bar configuration for the token, it's not important at all to reproduce...)_

**Versions**
FoundryVTT: [11.315]
DND5e: [3.0.2]
Ready Set Roll: [3.0.5]
libwrapper: [1.12.13.0]

Other Modules
None

**Comment by MangoFVTT** [comment]
@Phentei Before the update RSR was indeed skipping configuration dialogs and using its own roll config for resources, however this is no longer possible for RSR to do, and resource consumption is now handled entirely by the system (which is why the dialog shows up for all items like it used to only do for spells). As such, this ticket is not really related to RSR anymore.

I would recommend dropping a feature request in the dnd5e github to request a way to bypass the resource configuration dialog for items, as RSR now piggybacks off the default behaviour and if the config dialog is being skipped by the system, then it will be skipped by RSR as well.
