### ISSUE TITLE
[BUG] RSR damage buttons do not appear for other users.

### ISSUE THREAD

**Issue by Vengrath97** [MangoFVTT/fvtt-ready-set-roll-5e#362]
**Description**
Damage rolls triggered from other users will have error thrown
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/dcb31fb7-b1e3-46f3-b692-30a9798e0a41)
(in this instance, Koksuvi is the the user, that has no ownership over the token that rolled damage (the DM used the ability).
This results in RSR buttons not showing for players at all:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/a5dfbae1-1814-42b2-af9d-b7b4c98f0560)

**Steps to Reproduce**
1. Have 2 users on one Foundry server..
2. Have have one user roll something using RSR with damage buttons (for example an attack roll with a weapon).
3. Other users will have the error displayed, and RSR roll features (buttons) will not be visible for them.

**Versions**
 - Module: [3.0.7]
 - dnd5e: [3.0.5]
 - Foundry: [10.315]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
@Vengrath97 I haven't been able to reproduce this issue on my end. Players can see abilities rolled from creatures they have no ownership of just fine for me (see image below, left is the GM view and right is the player view, for rolling abilities from an NPC that the player has no ownership of).

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/36c497bb-32c2-473e-96bd-32a91dbd0394)

Can you check if this issue occurs for you with a fresh actor and using a fresh item created from scratch in 3.0.0? It's very likely that due to the significant changes between dnd5e 2.x and 3.x, migrations for module flags especially are mixed up. If this item existed before RSR 3.0.0 then that could be causing issues for you and the item would need to be recreated.

**Comment by Vengrath97** [comment]
This was an item that had been created long ago, so it might have been the case, but here's the weird thing: I've done some work on different worlds inbetween, and restarted the foundry server (it's hosted of forgevtt). The very same item is working correctly now, with no changes done to the item, module configuration, etc; so I can't pin-point what fixed it for me. It works on other worlds too, and on old items also.

So i guess the issue could be closed as non-preproducible.

**Comment by MangoFVTT** [comment]
Hmmm interesting. Could be that ForgeVTT was having issues sending update messages correctly between users, leading to issues with cards updating. Regardless, I will close the ticket for now and it can be re-opened if the issue resurfaces.
