### ISSUE TITLE
[BUG] Apply damage button shown twice when "always show" is active

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#370]
<img width="290" alt="image" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/72390280/e36cee3b-9d41-4729-8ac2-acd6076e3286">

When expanding the damage, there is another set of buttons that is redundant with the "always show buttons" option.

**Comment by MangoFVTT** [comment]
@nschoenwald this is intentional as per #323. The buttons below the total damage will apply the total damage, whereas the buttons below the specific damage tooltip will only apply that specific damage part. When there is only 1 damage type they do functionally the same thing, but when there are multiple damage types it allows users to apply the different parts of the damage equation separately if they wish, or in total by using the buttons outside the tooltip.

**Comment by nschoenwald** [comment]
@MangoFVTT Wouldn't it make sense not to show the buttons below the specific damage tooltip if there is only 1 damage type? That would look much cleaner.

**Comment by MangoFVTT** [comment]
Fair enough, I'll put it on the list as a feature then

**Comment by nschoenwald** [comment]
Awesome, thank you!

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
