### ISSUE TITLE
[BUG] Regression in Heavy Armor Master damage reduction

### ISSUE THREAD

**Issue by sapost** [MangoFVTT/fvtt-ready-set-roll-5e#375]
**Description**
After upgrading to 5e system 3.x and Ready Set Roll 3.x, the "click to apply damage" calculations don't account for the damage reduction granted by the Heavy Armor Master feat. This functionality was originally introduced in issue #177 . 

**Steps to Reproduce**
1. Roll damage from a nonmagical bludgeoning/piercing/slashing weapon.
2. Select a token for a character with the Heavy Armor Master feat.
3. Click the Ready Set Roll apply damage button

Expected result: Damage is applied but reduced by 3
Actual result: Full damage is applied

**Versions**
 - Module: 3.0.6
 - dnd5e: 3.0.2
 - Foundry: 11 stable, build 315

**Other Modules**
n/a

**Comment by MangoFVTT** [comment]
This is a known thing, and the "regression" is because RSR now uses the system's own apply damage instead of its own, as the functionality to calculate resistances/immunities, etc was introduced in dnd5e 3.0.x. The benefits of this are huge, as it means I no longer need to worry about developing duplicate functionality to stay inline with dnd5e, so I don't intend to change this again by introducing my own calculations on top.

Unfortunately, the by-product of this is that the functionality introduced in dnd5e 3.0.x does not yet calculate feats or effects such as Heavy Armor Master. I believe this is a planned feature in the near future, but you should make a ticket on the dnd5e github if there isn't one already to add this to the planned functionality. Once that happens, RSR will automatically work with it without needing any new changes.
