### ISSUE TITLE
[BUG] If u choose to always make 2 rolls of d20, module reacts to a summary of them, when calculates hit or miss

### ISSUE THREAD

**Issue by arsserge** [MangoFVTT/fvtt-ready-set-roll-5e#376]
If u choose to always make 2 rolls of d20, module reacts to a summary of them, when calculates hit or miss
<img width="286" alt="Screenshot 2024-02-21 at 00 17 59" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/128509251/7d94db33-f098-4dfc-95af-be71a3cea41c">

**Comment by MangoFVTT** [comment]
This is unfortunately kind of an inevitability. The system, nor really foundry as a whole, does not have a concept of "both these dice are equally valid but should be considered separate values for the total". The hit/miss indicators are generated entirely by the dnd5e system, and there's no way for me to give it a 2d20 without it considering the TOTAL of the 2d20 rather than each d20 separately.

If you wish to use the hit/miss indicators, and indeed many of the upcoming automation features in dnd5e, I strongly suggest moving away from forced dual rolls and making use of the retroactive advantage/disadvantage overlays to change your cards into dual rolls when needed, otherwise features such as this will never properly be able to work as expected.
