### ISSUE TITLE
[FEATURE] Other Formula Quick Roll

### ISSUE THREAD

**Issue by ItsDrafty** [MangoFVTT/fvtt-ready-set-roll-5e#377]
Hi there,

been using the module for ages and it's a must-have for me. 

It would be great if "Other Formula" could be rolled automatically to the chat just like damage/healing is. 

I find my players often have features that need a roll that requires math or scaling but isn't necessarily a a damage or healing roll. 

For example, I have a player who is playing the MCDM Talent and needs to roll a d4 each time he uses a power. It would be nice to have it rolled automatically in "other Formula" without having to click another button in chat to roll it.

If you can make that happen, we'd appreciate it!

Thanks,
Drafty

**Comment by MangoFVTT** [comment]
So the reason this is currently not implemented by RSR is because the dnd5e system ENFORCES a chat message to be outputted when rolling the "Other Formula" for some reason. With attacks, damage, etc, I can pass in a parameter that blocks a chat message from being created so I can put the result inside the same card instead, but with the Other Formula this is not currently possible:

```javascript
 async rollFormula({spellLevel}={}) {
    if ( !this.system.formula ) throw new Error("This Item does not have a formula to roll!");

    const rollConfig = {
      formula: this.system.formula,
      data: this.getRollData(),
      chatMessage: true
    };
```
Until this changes, my hands are tied. I'm currently asking in the dev-support threads to see why this is the case and hopefully get it resolved, but until then Other Formula has to stay as a separate roll.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release
