### ISSUE TITLE
[BUG] Damage lines and rolls with same type show as 1 line, not separated

### ISSUE THREAD

**Issue by leborat** [MangoFVTT/fvtt-ready-set-roll-5e#388]
**Description**
Multiple damage instances from rolls ie; rogue attack damage + sneak attack damage, or 1handed and 2 handed rolls all show under 1 line rather than separated like they were previously. 

See imgur image for reference: https://imgur.com/a/s9JpSXm

**Steps to Reproduce**
1. Go to character sheet
2. Click on any item roll with multiple damage lines
3. Scroll down to most recent chat display of damage rolls
4. See that all damage calculations are placed under 1 line despite having multiple separate rolls.

**Versions**
 - Module: [3.0.10]
 - dnd5e: [3.0.3]
 - Foundry: [11.313]

**Other Modules**
I disabled all other modules and found the issue still there

**Comment by MangoFVTT** [comment]
@leborat this is a dnd5e issue not an RSR issue. For some reason it was decided to collect all damage of the same type into one group by the damage function, and since RSR now relies purely on system calculations to display things (for maintenance and compatibility reasons), it therefore displays that damage as the same group. I recommend making an issue for this on the dnd5e github and complaining that damage shouldn't be randomly collected into a single group if specifically made separate in the item card (I agree by the way).
