### ISSUE TITLE
[BUG] GM attack rolls not showing on player side

### ISSUE THREAD

**Issue by Moonshaft** [MangoFVTT/fvtt-ready-set-roll-5e#395]
**Description**
I assume that this is a bug instead of an intended feature? Previously, whenever I rolled an attack with an NPC the players would see a gray box showing that I rolled a mystery action/dice (repeated if I was rolling consecutively for Multiattack). However, now the attack rolls appear to be completely hidden from the player's view. They can only see if I roll something like an attribute check/save or a skill check.

See below. The left hand side is what the player sees and the right hand side is what the GM sees. Is there an option that I'm being blind in locating that will show the players that I'm rolling a mystery attack (much like how the attributes/skills look)?

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/20808506/ae486d1d-1492-4044-915a-d6c68032adf8)

**Versions**
 - Module: 3.0.11
 - dnd5e: 3.0.1 & 3.0.3 (I updated to 0.3 hoping it would fix it)
 - Foundry: 11.315

**Other Modules**
No other modules are active, only Ready Set Roll. After testing, this exclusively happens when Ready Set Roll is active. The hidden attack rolls show up in chat if the mod is disabled.

**Comment by MangoFVTT** [comment]
This is a tricky bug to fix because it's not technically a bug. In the core system, item cards by default DON'T show anything to players when rolled in secret. They only show something when you click the relevant Attack, Damage, etc. buttons, and then those individual rolls are shown as ??? cards. 

Since RSR follows default system behaviour, it too doesn't show anything for item cards, but because it has no child cards to add, this means nothing at all is shown when an item is rolled in secret via RSR. This makes fixing this a bit tricky, because I can't override default system behaviour for not showing item cards, as far as I know anyway.

**Comment by Moonshaft** [comment]
That makes sense. Thanks for confirming! In the mean time Dice So Nice! still plays the sound associated with the hidden rolls so there will be at least some level of communication on what I'm doing other than "I'm going to try and hit you three times--be a dear and don't cast Shield."

**Comment by MangoFVTT** [comment]
This issue is no longer happening in dnd5e 3.3.1 and RSR 3.1.1+. Item rolls now correctly show the ??? message when rolled privately.

![image](https://github.com/user-attachments/assets/c3fd9ff2-0d60-4564-bca2-e497d1ce453c)
