### ISSUE TITLE
[FEATURE] Quick Roll for Damage Enricher Rolls

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#400]
**Is your feature request related to a problem? Please describe.**
You can fast forward most rolls in the game, but damage rolls originating from a Enricher arent fast forwarded

**Describe the solution you'd like**
An option within the settings that allows you to fast forward Damage Rolls from an Enricher.

**Describe alternatives you've considered**
Just doing awfully slow *he says in a drama queen voice*.

**Additional context**

**Comment by MangoFVTT** [comment]
Since damage enrichers are a vanilla roll, you can always hold the default vanilla modifiers to fast forward (I believe it is shift?) and that should automatically work. There's not presently a way for RSR to pass fast forward options to the damage enricher code in the system unfortunately, so this is impossible for RSR to fix correctly for now
