### ISSUE TITLE
[BUG] Lost ability to skip resource consumption prompt

### ISSUE THREAD

**Issue by oestred** [MangoFVTT/fvtt-ready-set-roll-5e#409]
I Recently upgraded to the latest DND5E 3.x version.  On a class feature with resource consumption, my player says his Flurry of Blows which uses a resource of KI used to not pop up the prompt asking to consume a resource where he has to click the 'use ability' button.  Similar thing happens on an item that uses a resource or limited use.  It helps to make it less clicks or steps for doing things.

After asking around, I think it was RSR that was making it not ask that before.   (does that sound right?)
Was that a feature lost with the 3.x upgrade by accident or it just got missed during the update?

Latest Foundry 11.x, latets DND5E 3.x, latest RSR module update

Thank you!

**Comment by MangoFVTT** [comment]
This is a feature it is simply no longer possible due to changes in 3.0 and how it handles consumption. RSR now fully relies on the system to handle resource consumption. If you wish for a way to fast forward the usage configuration popup, it would be best to request it as a feature on the dnd5e github, and then RSR will automatically work off of that.
