### ISSUE TITLE
[FEATURE] Options for passive on skill checks

### ISSUE THREAD

**Issue by Lexicality** [MangoFVTT/fvtt-ready-set-roll-5e#410]
**Is your feature request related to a problem? Please describe.**
My group runs the house rule that you cannot roll perception lower than your passive score. Currently either the DM needs to remember to check people's passives before asking them to roll or the player needs to remember to tell the DM if their roll is lower than their passive.

**Describe the solution you'd like**
Either

- A toggle per-ability to specify that the player can't roll below a 10
- The roll card in the chat shows the passive ability in brackets eg ![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/847422/24260312-b7ab-4bfb-9ea0-2bb656bc488f)

**Describe alternatives you've considered**
I've written a macro (`/roll {1d20,10}kh + @skills.prc.total # Perception Skill Check`) but it doesn't support any of the features from Ready Set Roll
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/847422/efb69083-6ca9-46a3-9f87-e675ff4117cd)

**Additional context**
If there's a way to make the macro support roll editing (eg advantage/disadvantage) then I'd settle for that

**Comment by MangoFVTT** [comment]
There's not really any way for RSR to pick up an arbitrary roll from a macro and process it properly, because such rolls have no attached identifiers and data to mark them as ability checks or skill checks, and so RSR wouldn't know what the type of roll is and how to handle it.

However, I am 100% positive there is a way to make a macro that takes your selected actor and actually rolls the `rollSkill` function for that actor, at which point you can manually pass `reliableTalent: true` in the `rollSkill` options, which would accomplish exactly what you're doing here (minimum roll of 10), while also adding RSR content (if the appropriate setting is enabled). 

My advice is to ask in the dnd5e discord channel about how to make such a macro, there are plenty of very talented people there who can write one up for you very quickly if you explain the results you want. Feel free to copy paste the paragraph above for your explanation, people who are familiar with the system should know what it all means if you yourself are unfamiliar.

**Comment by Lexicality** [comment]
Cheers,
```javascript
actor.rollSkill("prc", { reliableTalent: true })
```
works perfectly
