### ISSUE TITLE
Improved support for 3.1 system-default combat damage buttons

### ISSUE THREAD

**Issue by apoapostolov** [MangoFVTT/fvtt-ready-set-roll-5e#418]
In D&D 3.1, the system has added its own target damage support very similar to what Ready Set Roll had implemented before. You way want to default to it if the system is 3.1 and newer. It still lacks some QoL polish and maybe you can help those who want to use it. 

The feature always starts with the target damage inside a drawer that needs to be manually opened

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/4083812/4a0b51f4-74b8-43e3-a064-987ed5c0caf6)

A fix that makes it always opened would be greatly appreciated.

**Comment by MangoFVTT** [comment]
There is no intention to remove RSR damage apply buttons for the time being, as the system version still lacks various features I consider crucial, specifically the ability to apply damage by the individual fields rather than as a whole total. It also doesn't allow applying to both targets and selected tokens simultaneously, or to select targets retroactively. For now, RSR will remain as is. If you wish to not see RSR apply buttons, they can always be disabled via the module settings.

As for the tray defaulting to open, that is a ticket for the dnd5e system that is already being worked on: https://github.com/foundryvtt/dnd5e/issues/3291
