### ISSUE TITLE
[FEATURE] Damage type

### ISSUE THREAD

**Issue by CrazierIvan** [MangoFVTT/fvtt-ready-set-roll-5e#423]
**Is your feature request related to a problem? Please describe.**
In the older version of Ready Set Roll, it displayed not only the damage number, but also the damage type. I'd like that feature back.
https://i.imgur.com/LX64YC5.png

**Describe the solution you'd like**
Have the damage type displayed near the number, or below it.

**Comment by CrazierIvan** [comment]
Furthermore, another thing that I'd like to be always displayed is Context. Context is useful, and I don't think you should have to click on the damage roll to display it.
There is a huge difference between this

https://i.imgur.com/hkgzv55.png

And this

https://i.imgur.com/2Ka1fXo.png

**Comment by CrazierIvan** [comment]
Additionally, I miss "Repeat the roll" button much. I believe it was a part of this module, yes?

**Comment by MangoFVTT** [comment]
Damage type is displayed inside the damage tooltip, since that is also where the separation of damages by type happens. The same is true for the context, which is shown per damage field in the tooltip.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/057a74ad-5a2e-481e-ac8b-bf8f127a63b7)

The overall style of the tooltip and damage box are overlaid onto the dnd5e 3.0 system damage box, rather than created from scratch like older versions of RSR. The reasons for this are many, but the basics are that it is way easier to maintain this module between updates of the dnd5e system this way. I understand that it is an extra click to see your separate damages this way, but this is the direction that the system has decided to take in presenting such information, and RSR will remain more closely aligned with that in future.

> Additionally, I miss "Repeat the roll" button much. I believe it was a part of this module, yes?

It is, and as mentioned in the documentation is currently disabled due to the 3.x update. It will be re-added in future once I have the time to get it to work.

**Comment by CrazierIvan** [comment]
Can there at least be an option to have the tooltips expanded by default?

**Comment by MangoFVTT** [comment]
That request would need to be made to the dnd5e base system github, since the tooltip is generated by the system and not by RSR
