### ISSUE TITLE
[BUG] Damage type context bug.

### ISSUE THREAD

**Issue by CrazierIvan** [MangoFVTT/fvtt-ready-set-roll-5e#424]
**Description**
If an item or a spell has two formulas, both dealing the same type of damage, the context does not display. 

https://i.imgur.com/p3ruyfa.png 
Turns into
https://i.imgur.com/utCXpBp.png

When it should look like this
https://i.imgur.com/3WevjUg.png

**Steps to Reproduce**
Set up a spell or item that has two damage formulas - one with one type of damage, the other with another (or no type at all). Observe the context display properly. Now change both formulas to do the same type of damage, and observe no context.

**Versions**
 - Module: 3.014
 - dnd5e: 3.1.1
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
This is a byproduct of this issue with the dnd5e base system: https://github.com/foundryvtt/dnd5e/issues/3199. Since damage fields of the same type are combined into one tooltip by the system, only the first context can display at present. When the system implements separation of damage of the same type (or rather, _if_), RSR will display contexts correctly again. Until then, there isn't anything I can do to fix this.
