### ISSUE TITLE
[FEATURE] being able when applying damage to not apply critical damage

### ISSUE THREAD

**Issue by andregu** [MangoFVTT/fvtt-ready-set-roll-5e#44]
![Untitled](https://user-images.githubusercontent.com/3976074/189873682-0205b839-54a4-4948-bfda-30622a44c292.png)

Great module, thank you so much for your work.

something i noticed, when you dual roll and one of them is a nat 20 the critical damage will be roled too, but what if that roll is rolled at disavantage? BR used to have a dialog show up asking if you wanted to apply the critical damage, is it possible to have something similar? or another way to choose not to apply the critical damage?

**Comment by MangoFVTT** [comment]
This is implemented as of Release 1.3.0 when using the Apply Damage buttons
![image](https://user-images.githubusercontent.com/110994627/189886932-abb62cd7-5736-4c25-8b95-e37c14db8b8a.png)

In order to have the dialog appear, make sure this setting is not enabled:
![image](https://user-images.githubusercontent.com/110994627/189886997-4ed4aa20-5dc8-4e08-92bf-08dac4f16c8e.png)
