### ISSUE TITLE
[BUG] When chat log is "popped out", RSR doubles all dice rolls

### ISSUE THREAD

**Issue by asherett** [MangoFVTT/fvtt-ready-set-roll-5e#511]
**Description**
When the chat log is "popped out" (by right clicking the log icon), RSR starts acting very strangely, rolling all dice twice.

**Steps to Reproduce**
1. Rightclick the chat log icon (the two chat bubbles) in the top right menu
2. Make any attack roll or similar
3. If you have Dice so Nice enabled, you'll see 4 d20 rolls, and double all damage dice rolled
4. See the chat card(s): damage has been rolled twice

While being relatively codeblind, I'm guessing this is because 2 chat cards are generated, and RSR thus does its work twice...?

**Versions**
 - Module: [3.3.2]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Other Modules**
The issue exists with RSR as only active module.

**Comment by MangoFVTT** [comment]
@asherett I'm not seeing any double rolls on the RSR side, chat messages seem to be in sync across the popup and embedded version of the chat log and I am able to back and forth manipulate and use messages in both without issue. 

![image](https://github.com/user-attachments/assets/634b01e8-0c4c-4db0-80e0-ed80cde8e7b2)

Is the issue you're having specifically that DSN is rolling things twice? You say that RSR is the only active module, but your repro steps indicate having DSN active as well. If yes, this may be more due to DSN than RSR, but I can better check the bug with more information. If this is unrelated to DSN, some more information about what settings you have active, screenshots of your problem, etc, would all be helpful

**Comment by asherett** [comment]
Interesting. I saw the issue with only RSR active, DSN was only to see double d20s rolled as RSR only showed one. Damage dice were consistently rolled twice. I'll test more and give more info this evening, in 8-9 hours hopefully.

**Comment by asherett** [comment]
![image](https://github.com/user-attachments/assets/740ee17d-7e26-4ae9-8193-da60f2a0ecdc)
This is what I see on all rolls. Notice the whole damage formula is doubled.

And with chatlog not popped out:
![image](https://github.com/user-attachments/assets/85281087-68b2-430b-b8e0-a41b43a30276)

No errors are generated in console. The only module active in the screenshot is RSR.
I have also tested in a brand new empty world with the same result:
![image](https://github.com/user-attachments/assets/aa2337d0-e91c-4b3d-8f57-ac801f8adf0d)

**Comment by asherett** [comment]
I have now tested with RSR 3.3.3, and in the following browsers:
Firefox 131.0.3
Chrome 130.0.6723.70
Edge 130.0.2849.52

Same issue present in all.

**Comment by MangoFVTT** [comment]
Found the problem, it specifically only happens when manual damage is set to never. I've pushed a fix that should be in the next release
