### ISSUE TITLE
[BUG] Enabling Quick Rolls for Activities skips the Configure Roll dialog of the damage roll

### ISSUE THREAD

**Issue by Louis-PhilippeGentile** [MangoFVTT/fvtt-ready-set-roll-5e#523]
**Description**
In an Attack Activity, when defining a damage part, multiple damage types can be chosen. This affects the `Configure Roll` dialog (shown when rolling damage) by allowing that damage part to have a dropdown menu containing all damage types chosen for that specific damage part. See screenshot below for `Configure Roll` dialog:
![Screenshot 2024-10-26 163455](https://github.com/user-attachments/assets/0f5f6ac4-bf44-4853-b1fd-b0cf91e03a2e)

When `Enable Quick Roll for Activities` is enabled, the attack roll is made automatically, but the damage *may* not be rolled automatically, based on the user's setting of `Roll Damage Manually`. 

If `Roll Damage Manually` is set to `Never`, then the damage is rolled when the `Attack` activity is used, using the last selected damage type for each damage part of the `Attack` activity, with the `Configure Roll` dialog being skipped. 

If `Roll Damage Manually` is set to `Attack Rolls` or `Always`, then the `Configure Roll` dialog is *also* skipped, using the last selected damage type for each damage part of the `Attack` activity.  I would not consider this intentional, as I expect that if `Roll Damage Manually` is set to allow the user to roll their damage manually, then they should also be able to configure their damage roll through the `Configure Roll` dialog.

**Steps to Reproduce**
1. In the Ready Set Roll 5e module settings, set `Enable Quick Roll for Activities` to `true` and `Roll Damage Manually` to either `Attack Rolls` or `Always`
2. Create/Add an item with an `Attack` activity
3. In the `Attack` activity, define a damage part with more than one damage type (Ex. Slashing *OR* Force) (See screenshot for example)
![Screenshot 2024-10-26 162952](https://github.com/user-attachments/assets/1b9d3dcc-17ef-49bb-acc9-46952a598fe1)
4. Use the item
5. Click on the damage dialog 
6. The damage is rolled, but the user did not get to choose the damage type for each damage part
![Screenshot 2024-10-26 163252](https://github.com/user-attachments/assets/6f8e2319-70b9-48fc-983e-6635640b4bd0)

**Versions**
 - Module: [3.3.4]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Other Modules**
N/A

**Comment by MangoFVTT** [comment]
This is actually in-line with the expected behaviour of fast forwarding in general in dnd5e: the first option added is taken as the default. If you fast forward a vanilla damage roll, the same thing happens: the drop down does not appear and whatever damage type you added is selected first. Therefore, this is behaving as intended in RSR. The point is to by default remove all dialogs and fast forward as much as possible.

As a solution to what you wish to do while keeping other RSR functionality, you can do the following:
1. Enable Content on Vanilla Rolls (turn the setting to true)
2. Roll the item you want to select damage for without quick rolling (default is to hold Alt while clicking)
3. Roll damage from the damage button, this will give you the usual dialog where you can select the damage type
4. The damage should be updated in-line into the chat message with the selected type
