### ISSUE TITLE
[FEATURE] Apply damage buttons are confusing for players

### ISSUE THREAD

**Issue by vt-tom** [MangoFVTT/fvtt-ready-set-roll-5e#55]
**Is your feature request related to a problem? Please describe.**
Somehow the apply dammage/healing buttons are a little bit confusing for the players. If the GM attacks the player, it makes totally sense, that the player can use them to apply the damage to his token, because the token is mostly in his fokus.

But if he attacks and enemy, the apply damage would also effect his token, because he cannot select the enemy token.

**Describe the solution you'd like**
If the Ticket with damage applying to target tokens is implemented, then this ticket can be closed!

**Describe alternatives you've considered**
Maybe its possibile to get a permission for the apply damage buttons? So i can use them only as a GM in my group?

**Comment by MangoFVTT** [comment]
This was a limitation of BetterRolls as well, in that the idea is to inherently prohibit players from applying damage to NPCs/monsters (since this could be abused). With the way the permissions currently work, players can only apply damage to themselves or tokens they control. Limiting apply buttons to only GMs woud take away this ability for players to quickly apply damage to themselves, which seems unproductive.

I do intend to look at the targeting damage ticket, and will close this ticket in unison if that is applied since it is effectively a fix for this.

**Comment by MangoFVTT** [comment]
Resolved by #45.
