### ISSUE TITLE
Customizing Crit Damage

### ISSUE THREAD

**Issue by MyklKelsey** [MangoFVTT/fvtt-ready-set-roll-5e#56]
**Is your feature request related to a problem? Please describe.**
The little "+" "Click to roll critical damage" is incorrect when I have a weapon with non-standard damage

**Describe the solution you'd like**
I created a "Vicious Longsword" that does 2d8kh damage instead of merely 2d8. It works great, and is truly "vicious" >:-)
But when I click the "+" for a crit it rolls 2d8. That's nice and all, but couldn't there be a way to override with a custom crit damage? I'd really like something like "2d8kh + 2d8kh + @mod" <<< if you know what I mean. ;-)

**Describe alternatives you've considered**
The only alternate I can think of is having the player roll it manually. Computers can do so much more than that though!

**Additional context**
I've probably given too much context, so I'll quit while I'm ahead.

**Comment by MangoFVTT** [comment]
This is actually unintended, there was a bug where modifiers on the first damage roll would be incorrectly ignored. Similarly, the customizable critical bonus damage (which you can enter in the field shown in the image even in the default system btw) was also being ignored. 

![image](https://user-images.githubusercontent.com/110994627/190447426-2309de38-92a9-4b90-9379-47f83c3f6a90.png)

Both of these issues have been fixed by #57 and will be in the next hotfix release

**Comment by MangoFVTT** [comment]
This issue is now fixed with Release 1.3.4
