### ISSUE TITLE
[BUG] Setting "Critical Damage Maximize Dice" wrong application

### ISSUE THREAD

**Issue by spirritus** [MangoFVTT/fvtt-ready-set-roll-5e#63]
**Description**
If the setting "Critical Damage Maximize Dice" in the DnD settings is turned on, the damage dice appear twice,
once maximized and once rolled. For example attacking with a mace would yield:
* regular 1d6+STR
* crit 1d6+STR+1d6(crit)

Turning the setting on should yield 1d6+STR+max(1d6), however this does not happen, instead 1d6+STR+max(1d6)+1d6(crit) is used.

**Versions**
 - Module: 1.3.5
 - dnd5e: 2.0.2
 - Foundry: 10.285

**Other Modules**
midi-qol but roll automation is disabled

**Comment by MangoFVTT** [comment]
I am unable to reproduce this error on a clean project that only uses RSR, as shown:

![image](https://user-images.githubusercontent.com/110994627/190963222-db80dad8-0e84-489d-856d-4248936db512.png)

As you can see, dice are being maximised as expected and no additional dice are being rolled. I would firstly check that you have no additional Melee Critical Damage Dice set in the actor's special traits, and nothing set in the item's Extra Critical Hit Damage.

![image](https://user-images.githubusercontent.com/110994627/190963304-1966d296-82ed-471d-a2d1-2d8276ab770d.png)
![image](https://user-images.githubusercontent.com/110994627/190963330-1c0bf620-a455-4252-aa82-80903358ae1f.png)

If neither of these are the case, then it is likely that midi-qol is the cause of the issue. Even with disabling roll automation, midi-qol does a tonne of things under the hood that can easily cause problems with other roll automation modules. Compatibility between the two modules is not supported (at least yet), since it would require the author of midi-qol to explicitly integrate this module's rolling capabilities into their module. There is almost nothing I can do on my end, as far as I know. Until then, it is best not to cross the streams.
