### ISSUE TITLE
[BUG] Minor Issue with DAE

### ISSUE THREAD

**Issue by AaronRakuu** [MangoFVTT/fvtt-ready-set-roll-5e#64]
Hey! Thank you for adding DAE compatibility, but there's a very small bug which I'm encountering. It looks like when 2 different DAE effects modify the damage field, then it seems to bug out and do neither.

For example, for a hexblade, I set up a toggle-able effect which adds 1d6 necrotic, which works with Ready Set Roll now! Similarly I set up hexblade's curse, which adds @prof damage, which also works with Ready Set Roll! But when both are active at the same time, the damage seems to bug out and add neither- doing a 0[necrotic] instead.

![e](https://user-images.githubusercontent.com/113914690/191031692-563243d9-e6bc-4648-bd9c-9f8190750829.jpg)

**Comment by MangoFVTT** [comment]
I haven't been able to reproduce this issue both with DAE or with normal Foundry effects added to the actor (see image). Tried with various bonus types (melee, ranged, spell attack, etc) and other different items as well. None had this issue and bonus damage was always applied correctly.

![image](https://user-images.githubusercontent.com/110994627/191067666-f4eae1a0-e8bd-42eb-8923-63b40331fd46.png)

Are you using another module that affects dice rolls? For example midi-qol?

**Comment by MangoFVTT** [comment]
Further investigation has led me to actually find the cause for this. This is actually caused by a bug in how Foundry applies effects. When you have multiple effects that `Add`, you have to manually add a `+` before the formula you are adding, otherwise Foundry simply concatenates them as text (creating, for example in this case: `@prof1d6`, instead of `@prof + 1d6`), which then gets evaluated wrong and outputs as `0`. For the solution to this problem, you must add `+`s manually to your effects.

Without +:
![image](https://user-images.githubusercontent.com/110994627/191068812-068d2fea-d920-4830-be9f-ed27df11e09d.png)

With +:
![image](https://user-images.githubusercontent.com/110994627/191069260-6daf2f2b-e9e8-43b8-9509-9d1b18094eee.png)
