### ISSUE TITLE
Alt roll and no quick roll on different buttons?

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#70]
At the moment if you have alternate rolls then it disables the bypass used to not roll a quick roll since both use the same button. is it possible to have the possibility to configure which button is used for which.

**Comment by MangoFVTT** [comment]
This is unfortunately not possible, due to limitations with Foundry/Javascript. Only Ctrl, Shift, and Alt are picked up as modifier keys by a mouse click event, and all 3 are in use, so there is no alternative key that is possible to use for allowing default rolls without removing some other functionality.

As a workaround, one of the planned features is to re-add the "sheet buttons" that Better Rolls had, which amongst other things allow for rolling a default Foundry roll directly from the item even if alternate rolls are enabled.
